version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.10
    environment:
    working_directory: ~/MacSetup
    steps:
      - checkout
      - run:
          name: Test Script Invocation
          # Ensure the script can be successfully invoked
          # but then immediately exit to test only
          # initialization/invocation.
          command: printf 'n\n' | ./install.sh
  container_build:
    docker:
      - image: docker:default
    working_directory: ~/MacSetup
    steps:
      - setup_remote_docker:
          version: default
          docker_layer_caching: true
      - checkout
      - run: docker build -t macsetup .
      - run: docker system prune --force
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - container_build
